import { reactRouter } from "@react-router/dev/vite";
import path from "node:path";
import { defineConfig, PluginOption } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(({ mode, isSsrBuild }) => ({
  build: {
    minify: true,
    rollupOptions: {
      onwarn(warning, defaultHandler) {
        if (warning.code === "SOURCEMAP_ERROR") {
          return;
        }

        defaultHandler(warning);
      },
      ...(isSsrBuild && { input: "./server/app.ts" }),
    },
  },
  define: {
    global: "globalThis",
  },
  ssr: {
    noExternal: [
      "@carbon/auth",
      "@carbon/database",
      "@carbon/documents",
      "@carbon/ee",
      "@carbon/form",
      "@carbon/jobs",
      "@carbon/kv",
      "@carbon/lib",
      "@carbon/logger",
      "@carbon/notifications",
      "@carbon/react",
      "@carbon/remix",
      "@carbon/stripe",
      "@carbon/tailwind",
      "@carbon/tiptap",
      "@carbon/utils",
      "@tanstack/react-query",
      "@tanstack/react-table",
      "@tanstack/react-virtual",
      "@vercel/analytics",
      "@vercel/react-router",
      "@react-aria/i18n",
      "react-markdown",
      "remark-gfm",
      "rehype-raw",
      "rehype-sanitize",
      "framer-motion",
      "isbot",
      "nanoid",
      "nanostores",
      "recharts",
      "ai",
      "motion-number",
      "react-dropzone",
      "react-icons",
      "react-phone-number-input",
      "tailwind-merge",
      "class-variance-authority",
      "tiny-invariant",
      "unified",
      "unist-util-visit",
      "lodash.template",
      "react-colorful",
      "react-confetti-explosion",
      "react-resizable-panels",
      "intl-parse-accept-language",
      "kysely",
    ],
  },
  server: {
    port: 3001,
    allowedHosts: [".ngrok-free.app", ".w.modal.host", ".w.modal.dev"],
  },
  plugins: [reactRouter(), tsconfigPaths()] as PluginOption[],
  resolve: {
    alias: {
      "@carbon/auth/auth.server": path.resolve(__dirname, "../../packages/auth/src/services/auth.server.ts"),
      "@carbon/auth/company.server": path.resolve(__dirname, "../../packages/auth/src/services/company.server.ts"),
      "@carbon/auth/session.server": path.resolve(__dirname, "../../packages/auth/src/services/session.server.ts"),
      "@carbon/auth/users.server": path.resolve(__dirname, "../../packages/auth/src/services/users.server.ts"),
      "@carbon/auth/verification.server": path.resolve(__dirname, "../../packages/auth/src/services/verification.server.ts"),
      "@carbon/auth$": path.resolve(__dirname, "../../packages/auth/src/index.ts"),
      "@carbon/auth": path.resolve(__dirname, "../../packages/auth/src"),
      "@carbon/database$": path.resolve(__dirname, "../../packages/database/src/index.ts"),
      "@carbon/database": path.resolve(__dirname, "../../packages/database/src"),
      "@carbon/documents/qr": path.resolve(__dirname, "../../packages/documents/src/qr/qr-code.ts"),
      "@carbon/documents": path.resolve(__dirname, "../../packages/documents/src"),
      "@carbon/ee/accounting": path.resolve(__dirname, "../../packages/ee/src/accounting/index.ts"),
      "@carbon/ee/jira": path.resolve(__dirname, "../../packages/ee/src/jira/lib/index.ts"),
      "@carbon/ee/linear": path.resolve(__dirname, "../../packages/ee/src/linear/lib/index.ts"),
      "@carbon/ee/notifications": path.resolve(__dirname, "../../packages/ee/src/notifications/index.ts"),
      "@carbon/ee/onshape": path.resolve(__dirname, "../../packages/ee/src/onshape/lib/index.ts"),
      "@carbon/ee/paperless-parts": path.resolve(__dirname, "../../packages/ee/src/paperless-parts/lib/index.ts"),
      "@carbon/ee/slack/messages": path.resolve(__dirname, "../../packages/ee/src/slack/lib/messages.ts"),
      "@carbon/ee$": path.resolve(__dirname, "../../packages/ee/src/index.ts"),
      "@carbon/ee": path.resolve(__dirname, "../../packages/ee/src"),
      "@carbon/form$": path.resolve(__dirname, "../../packages/form/src/index.tsx"),
      "@carbon/form": path.resolve(__dirname, "../../packages/form/src"),
      "@carbon/jobs": path.resolve(__dirname, "../../packages/jobs"),
      "@carbon/kv$": path.resolve(__dirname, "../../packages/kv/src/index.ts"),
      "@carbon/kv": path.resolve(__dirname, "../../packages/kv/src"),
      "@carbon/lib/resend.server": path.resolve(__dirname, "../../packages/lib/src/resend.server.ts"),
      "@carbon/lib/slack.server": path.resolve(__dirname, "../../packages/lib/src/slack.server.ts"),
      "@carbon/lib/twenty.server": path.resolve(__dirname, "../../packages/lib/src/twenty.server.ts"),
      "@carbon/lib": path.resolve(__dirname, "../../packages/lib/src"),
      "@carbon/logger$": path.resolve(__dirname, "../../packages/logger/src/index.ts"),
      "@carbon/logger": path.resolve(__dirname, "../../packages/logger/src"),
      "@carbon/notifications$": path.resolve(__dirname, "../../packages/notifications/src/index.ts"),
      "@carbon/notifications": path.resolve(__dirname, "../../packages/notifications/src"),
      "@carbon/react$": path.resolve(__dirname, "../../packages/react/src/index.tsx"),
      "@carbon/react": path.resolve(__dirname, "../../packages/react/src"),
      "@carbon/remix$": path.resolve(__dirname, "../../packages/remix/src/index.ts"),
      "@carbon/remix": path.resolve(__dirname, "../../packages/remix/src"),
      "@carbon/stripe/stripe.server": path.resolve(__dirname, "../../packages/stripe/src/stripe.server.ts"),
      "@carbon/stripe": path.resolve(__dirname, "../../packages/stripe/src"),
      "@carbon/tailwind": path.resolve(__dirname, "../../packages/tailwind"),
      "@carbon/tiptap$": path.resolve(__dirname, "../../packages/tiptap/src/index.ts"),
      "@carbon/tiptap": path.resolve(__dirname, "../../packages/tiptap/src"),
      "@carbon/utils$": path.resolve(__dirname, "../../packages/utils/src/index.ts"),
      "@carbon/utils": path.resolve(__dirname, "../../packages/utils/src"),
    },
  },
}));
